services:
  - type: web
    name: project-black-box-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend

    envVars:
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: Packers2025!
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: backend
      - key: DB_SECRET_KEY
        value: Blackbox
