import type { Metadata } from "next";
import {  Sixtyfour } from "next/font/google";
import 'animate.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/globals.css';
import BootstrapClient from "@/utils/BootstrapClient";

const sixtyfourFont = Sixtyfour({
  variable: "--font-sixtyfour", // Define a custom CSS variable for the font
  subsets: ["latin"], // Specify the subsets you want (e.g., "latin", "cyrillic", etc.)
  display: "swap", // Optional: Controls font-display behavior
});


export const metadata: Metadata = {
  title: "Black Box",
  description: "Black Box is a fully immersive asmr platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sixtyfourFont.variable}`}>
        {children}
        <BootstrapClient /> 
      </body>
    </html>
  );
}


{/*
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Geist, Geist_Mono } from "next/font/google";
import '@/styles/globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Black Box",
  description: "Generated by create next app",
};
import BootstrapClient from '@/utils/BootstrapClient';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
*/}